# Generated by Django 4.2 on 2024-04-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='api.marca'),
        ),
    ]
