# Generated by Django 4.2 on 2024-04-08 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_available_product_cupon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad_usos', models.IntegerField(default=0)),
                ('cantidad_usos_limite', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_cupon',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='api.cupon'),
        ),
    ]
