# Generated by Django 4.2 on 2024-04-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cupon_alter_product_cupon'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cupon',
            table=None,
        ),
    ]
