# Generated by Django 4.2 on 2024-04-10 04:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_marca_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
